# Generated by Django 5.2.16 on 2026-07-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('started', models.BooleanField(default=False)),
                ('warned', models.BooleanField(default=False)),
            ],
        ),
    ]
