# Generated by Django 5.2.16 on 2026-07-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_message', models.TextField(default='ربات استارت شد!')),
                ('join_channel_message', models.TextField(default='{mention} برای ارسال پیام باید در {channel} عضو شوید.')),
            ],
        ),
    ]
