# Generated by Django 5.2.16 on 2026-07-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_botmessagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagesettings',
            name='collaboration_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
