# Generated by Django 5.2.16 on 2026-07-20 19:58

import botapp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_botmessagesettings_collaboration_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=botapp.models.generate_token, max_length=64, unique=True)),
                ('group_chat_id', models.BigIntegerField()),
                ('group_title', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('chat_title', models.CharField(blank=True, default='', max_length=255)),
                ('daily_prompt_limit', models.IntegerField(default=100)),
                ('tokens_used_today', models.IntegerField(default=0)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
