# Generated by Django 5.2.16 on 2026-07-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_chatlink_groupquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagesettings',
            name='bot_start_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='botmessagesettings',
            name='channel_join_required',
            field=models.BooleanField(default=True),
        ),
    ]
