# Generated by Django 5.2.16 on 2026-07-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_add_toggle_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('chat_title', models.CharField(blank=True, default='', max_length=255)),
                ('channel_join_required', models.BooleanField(default=True)),
                ('bot_start_required', models.BooleanField(default=True)),
                ('collaboration_enabled', models.BooleanField(default=True)),
                ('mandatory_channel', models.CharField(blank=True, default='', max_length=100)),
                ('group_admins', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user_id', models.BigIntegerField()),
                ('admin_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('old_value', models.BooleanField(null=True)),
                ('new_value', models.BooleanField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='botapp.groupsettings')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
