# Generated by Django 5.2.16 on 2026-07-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_groupsettings_allowed_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='max_warnings_action',
            field=models.CharField(choices=[('mute', 'Mute'), ('ban', 'Ban')], default='mute', max_length=10),
        ),
    ]
