# Generated by Django 5.2.16 on 2026-07-24 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0012_alter_groupsettings_welcome_message_groupschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcedMembershipRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_chat_id', models.BigIntegerField()),
                ('destination_chat_title', models.CharField(blank=True, default='', max_length=255)),
                ('destination_chat_type', models.CharField(blank=True, default='', max_length=20)),
                ('destination_username', models.CharField(blank=True, default='', max_length=32)),
                ('destination_join_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_by_user_id', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('bot_source_permissions_valid', models.BooleanField(default=False)),
                ('bot_destination_permissions_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forced_membership_rules', to='botapp.groupsettings')),
            ],
        ),
        migrations.CreateModel(
            name='ForcedMembershipInviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('invite_link', models.URLField(max_length=500, unique=True)),
                ('telegram_invite_link_name', models.CharField(blank=True, default='', max_length=100)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('member_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='botapp.forcedmembershiprule')),
            ],
        ),
        migrations.CreateModel(
            name='ForcedMembershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=40)),
                ('source_message_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_update_id', models.BigIntegerField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(blank=True, default='', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='botapp.forcedmembershiprule')),
            ],
        ),
        migrations.CreateModel(
            name='ForcedMembershipUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, default='', max_length=32)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('current_membership_status', models.CharField(default='unknown', max_length=32)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('first_warning_at', models.DateTimeField(blank=True, null=True)),
                ('last_warning_at', models.DateTimeField(blank=True, null=True)),
                ('first_joined_at', models.DateTimeField(blank=True, null=True)),
                ('last_joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('message_count_while_not_member', models.PositiveBigIntegerField(default=0)),
                ('deleted_message_count', models.PositiveBigIntegerField(default=0)),
                ('join_count', models.PositiveIntegerField(default=0)),
                ('leave_count', models.PositiveIntegerField(default=0)),
                ('rejoin_count', models.PositiveIntegerField(default=0)),
                ('has_ever_joined', models.BooleanField(default=False)),
                ('is_currently_member', models.BooleanField(default=False)),
                ('joined_via_tracked_invite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='botapp.forcedmembershiprule')),
            ],
        ),
        migrations.AddIndex(
            model_name='forcedmembershiprule',
            index=models.Index(fields=['source_group', 'is_active'], name='botapp_forc_source__9ffb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='forcedmembershiprule',
            index=models.Index(fields=['destination_chat_id', 'is_active'], name='botapp_forc_destina_3cc834_idx'),
        ),
        migrations.AddConstraint(
            model_name='forcedmembershiprule',
            constraint=models.UniqueConstraint(fields=('source_group', 'destination_chat_id'), name='uniq_forced_rule_source_destination'),
        ),
        migrations.AddIndex(
            model_name='forcedmembershipinvitelink',
            index=models.Index(fields=['rule', 'telegram_user_id', 'is_revoked'], name='botapp_forc_rule_id_d67515_idx'),
        ),
        migrations.AddIndex(
            model_name='forcedmembershipevent',
            index=models.Index(fields=['rule', 'event_type', 'created_at'], name='botapp_forc_rule_id_789828_idx'),
        ),
        migrations.AddIndex(
            model_name='forcedmembershipevent',
            index=models.Index(fields=['telegram_update_id'], name='botapp_forc_telegra_d35a8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='forcedmembershipevent',
            constraint=models.UniqueConstraint(fields=('rule', 'telegram_update_id'), name='uniq_forced_event_rule_update'),
        ),
        migrations.AddIndex(
            model_name='forcedmembershipuserstate',
            index=models.Index(fields=['rule', 'current_membership_status'], name='botapp_forc_rule_id_fc0016_idx'),
        ),
        migrations.AddIndex(
            model_name='forcedmembershipuserstate',
            index=models.Index(fields=['rule', 'has_ever_joined'], name='botapp_forc_rule_id_df8459_idx'),
        ),
        migrations.AddIndex(
            model_name='forcedmembershipuserstate',
            index=models.Index(fields=['rule', 'is_currently_member'], name='botapp_forc_rule_id_541929_idx'),
        ),
        migrations.AddConstraint(
            model_name='forcedmembershipuserstate',
            constraint=models.UniqueConstraint(fields=('rule', 'telegram_user_id'), name='uniq_forced_state_rule_user'),
        ),
    ]
