# Generated by Django 5.2.16 on 2026-07-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0013_forced_membership_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BotStartUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('first_message_at', models.DateTimeField(blank=True, null=True)),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('message_deleted_count', models.PositiveBigIntegerField(default=0)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_start_user_states', to='botapp.groupsettings')),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'telegram_user_id'], name='botapp_bots_group_i_e88239_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'telegram_user_id'), name='uniq_bot_start_state_group_user')],
            },
        ),
    ]
