# Generated by Django 5.2.16 on 2026-07-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0014_telegramuser_blocked_telegramuser_last_check_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botstartuserstate',
            name='warning_pending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BotStartGateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('telegram_update_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_start_gate_events', to='botapp.groupsettings')),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'telegram_user_id', 'status'], name='botapp_bots_group_i_382cb3_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'message_id'), name='uniq_bot_start_event_group_message')],
            },
        ),
    ]
