# Generated by Django 5.2.16 on 2026-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0015_botstartuserstate_warning_pending_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botstartuserstate',
            name='last_notice_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botstartuserstate',
            name='notice_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botstartuserstate',
            name='notice_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
