# Generated by Django 5.2.16 on 2026-07-24 18:43

from django.db import migrations, models
from django.utils import timezone


def backfill_welcomed_at(apps, schema_editor):
    TelegramUser = apps.get_model("botapp", "TelegramUser")
    TelegramUser.objects.filter(
        models.Q(started=True) | models.Q(blocked=True),
        welcomed_at__isnull=True,
    ).update(welcomed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0016_botstartuserstate_last_notice_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='welcomed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_welcomed_at, migrations.RunPython.noop),
    ]
