# Generated by Django 5.2.16 on 2026-07-27 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0018_harden_bot_start_gate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='telegram', max_length=32)),
                ('chat_id', models.BigIntegerField()),
                ('thread_id', models.BigIntegerField(default=0)),
                ('conversation_id', models.CharField(blank=True, default='', max_length=128)),
                ('chat_type', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'chat_id'], name='botapp_memo_platfor_d97dff_idx'), models.Index(fields=['last_activity_at'], name='botapp_memo_last_ac_bbd0c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'chat_id', 'thread_id', 'conversation_id'), name='unique_memory_conversation_identity')],
            },
        ),
        migrations.CreateModel(
            name='MemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_scope', models.CharField(choices=[('user', 'User global'), ('conversation', 'Conversation'), ('user_conversation', 'User conversation')], max_length=24)),
                ('category', models.CharField(choices=[('preference', 'Preference'), ('identity', 'Identity'), ('project', 'Project'), ('decision', 'Decision'), ('relationship', 'Relationship'), ('goal', 'Goal'), ('constraint', 'Constraint'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=32)),
                ('content', models.TextField()),
                ('normalized_content', models.TextField()),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('moderately_important', 'Moderately important'), ('unimportant', 'Unimportant')], max_length=24)),
                ('retention_level', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('critical', 'Critical')], max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('conversation_only', 'Conversation only'), ('user_global', 'User global'), ('group_shared', 'Group shared'), ('system_only', 'System only')], max_length=24)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_explicit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('deleted', 'Deleted'), ('archived', 'Archived'), ('pending_review', 'Pending review')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('mention_count', models.PositiveIntegerField(default=1)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_items', to='botapp.memoryconversation')),
                ('owner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_items', to='botapp.telegramuser')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_memory_items', to='botapp.telegramuser')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_items', to='botapp.memoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('old_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(blank=True, default='', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_lifecycle_events', to='botapp.telegramuser')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to='botapp.memoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='MemorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='telegram', max_length=32)),
                ('source_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('source_message_id', models.BigIntegerField(blank=True, null=True)),
                ('source_thread_id', models.BigIntegerField(default=0)),
                ('source_kind', models.CharField(default='message', max_length=32)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='botapp.memoryitem')),
                ('speaker_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_sources', to='botapp.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='member', max_length=32)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='botapp.memoryconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_memberships', to='botapp.telegramuser')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'last_activity_at'], name='botapp_memo_convers_6bee73_idx'), models.Index(fields=['user', 'last_activity_at'], name='botapp_memo_user_id_44b739_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='unique_memory_conversation_member')],
            },
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['owner_user', 'status', 'visibility'], name='botapp_memo_owner_u_6a5121_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['conversation', 'status', 'visibility'], name='botapp_memo_convers_cf02bc_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['retention_level', 'expires_at'], name='botapp_memo_retenti_4dffca_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['category', 'importance'], name='botapp_memo_categor_d92164_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='memory_item_confidence_between_zero_one'),
        ),
        migrations.AddIndex(
            model_name='memorylifecycleevent',
            index=models.Index(fields=['event_type', 'created_at'], name='botapp_memo_event_t_772193_idx'),
        ),
        migrations.AddIndex(
            model_name='memorylifecycleevent',
            index=models.Index(fields=['memory', 'created_at'], name='botapp_memo_memory__79a926_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysource',
            index=models.Index(fields=['source_chat_id', 'source_message_id'], name='botapp_memo_source__9ee189_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysource',
            index=models.Index(fields=['speaker_user', 'occurred_at'], name='botapp_memo_speaker_539e43_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorysource',
            constraint=models.UniqueConstraint(fields=('memory', 'platform', 'source_chat_id', 'source_message_id'), name='unique_memory_source_message'),
        ),
    ]
