# Generated by Django 5.2.16 on 2026-07-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0019_memory_core'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='memoryitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conversation__isnull', True), ('memory_scope', 'user'), ('visibility', 'user_global')), models.Q(('conversation__isnull', False), ('memory_scope__in', ['conversation', 'user_conversation']), models.Q(('visibility', 'user_global'), _negated=True)), _connector='OR'), name='memory_scope_visibility_consistent'),
        ),
    ]
