# Generated by Django 5.2.16 on 2026-08-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0020_memory_scope_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for the emoji, e.g., 'fire_animated'", max_length=50, unique=True)),
                ('custom_emoji_id', models.CharField(help_text='The actual custom emoji ID from Telegram', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Emoji',
                'verbose_name_plural': 'Custom Emojis',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='memoryconversation',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='welcome_emoji',
            field=models.ForeignKey(blank=True, help_text='Custom emoji to use in welcome messages for this group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcomed_in_groups', to='botapp.customemoji'),
        ),
    ]
