# Generated by Django 5.0.7 on 2026-08-01 19:07

from django.db import migrations

NEW_START_MESSAGE = "سلام ✨ من نویا هستم، دختر سینا. می‌تونید با پدر من [در این کانال](https://t.me/CoffeeMan_nej) حرف بزنید."
SPARKLE_EMOJI_ID = "5312526322733219436"  # This is a generic sparkle emoji ID, might need adjustment


def update_bot_settings(apps, schema_editor):
    BotMessageSettings = apps.get_model('botapp', 'BotMessageSettings')
    CustomEmoji = apps.get_model('botapp', 'CustomEmoji')

    # Create the sparkle emoji
    CustomEmoji.objects.get_or_create(
        name='sparkle',
        defaults={'custom_emoji_id': SPARKLE_EMOJI_ID}
    )

    # Update the start message
    settings, _ = BotMessageSettings.objects.get_or_create(pk=1)
    settings.start_message = NEW_START_MESSAGE
    settings.save()


def reverse_bot_settings(apps, schema_editor):
    # This is optional, but good practice. Revert to the old default.
    BotMessageSettings = apps.get_model('botapp', 'BotMessageSettings')
    settings, _ = BotMessageSettings.objects.get_or_create(pk=1)
    settings.start_message = "ربات استارت شد!"
    settings.save()

    # We don't delete the emoji on reverse, as it might be in use elsewhere.


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0021_emoji_feature'),
    ]

    operations = [
        migrations.RunPython(update_bot_settings, reverse_code=reverse_bot_settings),
    ]
