# Generated by Django 5.2.16 on 2026-08-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0022_update_start_message_and_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryconversation',
            name='summary',
        ),
    ]
