# Generated by Django 5.2.16 on 2026-08-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0023_remove_summary_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=36)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('requester_user_id', models.BigIntegerField()),
                ('requester_role', models.CharField(blank=True, default='', max_length=16)),
                ('original_command', models.CharField(blank=True, default='', max_length=2000)),
                ('parser_type', models.CharField(blank=True, default='', max_length=16)),
                ('detected_intent', models.CharField(blank=True, default='', max_length=64)),
                ('tool_name', models.CharField(blank=True, default='', max_length=64)),
                ('sanitized_parameters', models.JSONField(blank=True, default=dict)),
                ('risk_level', models.CharField(blank=True, default='', max_length=8)),
                ('confirmation_status', models.CharField(blank=True, default='', max_length=16)),
                ('execution_status', models.CharField(blank=True, default='', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_id', '-created_at'], name='botapp_agen_chat_id_e37a65_idx'), models.Index(fields=['tool_name', '-created_at'], name='botapp_agen_tool_na_163e95_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('request_message_id', models.BigIntegerField(blank=True, null=True)),
                ('confirmation_message_id', models.BigIntegerField(blank=True, null=True)),
                ('requester_user_id', models.BigIntegerField()),
                ('requester_name', models.CharField(blank=True, default='', max_length=255)),
                ('tool_name', models.CharField(max_length=64)),
                ('target_user_id', models.BigIntegerField(blank=True, null=True)),
                ('validated_parameters', models.JSONField(blank=True, default=dict)),
                ('human_summary', models.CharField(blank=True, default='', max_length=300)),
                ('risk_level', models.CharField(default='medium', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('executing', 'Executing'), ('executed', 'Executed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.CharField(blank=True, default='', max_length=500)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='botapp_agen_status_cecd29_idx'), models.Index(fields=['chat_id', 'requester_user_id', 'status'], name='botapp_agen_chat_id_29f483_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.BigIntegerField()),
                ('thread_id', models.BigIntegerField(default=0)),
                ('sender_user_id', models.BigIntegerField(blank=True, null=True)),
                ('sender_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_username', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField(blank=True, default='')),
                ('caption', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(blank=True, default='text', max_length=32)),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by_bot_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deletion_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_snapshots', to='botapp.moderationaction')),
            ],
            options={
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['chat_id', '-archived_at'], name='botapp_mess_chat_id_f2f85f_idx'), models.Index(fields=['chat_id', 'deleted_by_bot_at'], name='botapp_mess_chat_id_0c4d6d_idx')],
                'constraints': [models.UniqueConstraint(fields=('chat_id', 'message_id'), name='uniq_message_snapshot_chat_message')],
            },
        ),
    ]
