# Generated by Django 5.2.16 on 2026-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0024_agentauditlog_agentconfirmation_messagesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfirmation',
            name='executing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
