# Generated by Django 5.2.16 on 2026-08-04 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0025_agentconfirmation_executing_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsettings',
            name='max_warnings_action_duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
