# Generated by Django 5.2.16 on 2026-08-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0028_agentconfirmation_request_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfirmation',
            name='request_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
