# Generated by Django 5.2.16 on 2026-08-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0029_alter_agentconfirmation_request_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('day', models.DateField(db_index=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('unique_sender_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['chat_id', '-day'], name='botapp_chat_chat_id_f38482_idx')],
                'constraints': [models.UniqueConstraint(fields=('chat_id', 'day'), name='uniq_chat_daily_activity')],
            },
        ),
        migrations.CreateModel(
            name='ChatDailySender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('day', models.DateField(db_index=True)),
                ('user_id', models.BigIntegerField()),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['chat_id', 'day', '-message_count'], name='botapp_chat_chat_id_653779_idx')],
                'constraints': [models.UniqueConstraint(fields=('chat_id', 'day', 'user_id'), name='uniq_chat_daily_sender')],
            },
        ),
    ]
