# Generated by Django 5.2.16 on 2026-08-12 23:03

import django.core.validators
from django.db import migrations, models


def make_all_quotas_unlimited(apps, schema_editor):
    GroupQuota = apps.get_model("botapp", "GroupQuota")
    GroupQuota.objects.exclude(daily_prompt_limit=0).update(daily_prompt_limit=0)


class Migration(migrations.Migration):

    dependencies = [
        ("botapp", "0030_chat_daily_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupquota",
            name="daily_prompt_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Daily AI prompts allowed for this group. 0 = unlimited.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.RunPython(make_all_quotas_unlimited, migrations.RunPython.noop),
    ]
